name: "Classic books reformatted"
description: "Jekyll setup for turning markdown into HTML for simple classic books, e.g. from Project Gutenberg"

url: http://localhost:4000
baseurl: /classic-books

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments